### ISSUE TITLE
Bind to private interface by default

### ISSUE THREAD

**Issue by tennysontbardwell** [mpedramfar/zotra-server#4]
Should the server start on `0.0.0.0` by default (the public interface) rather than `127.0.0.1` (private) ([codelink](https://github.com/mpedramfar/zotra-server/blob/main/config/default.json5#L7))? I changed my local copy to `127.0.0.1` and it seemed to work fine.

**Comment by mpedramfar** [comment]
Thank you. I changed the default address to 127.0.0.1.
